### ISSUE TITLE
Is there a plan to support the HEVC in macOS 10.13.

### ISSUE THREAD

**Issue by AlickH** [packagesdev/savehollywood#1]
As the title said.
Thanks.

**Comment by SeanMSmith** [comment]
Please do consider allowing SaveHollywood to play HEVC-encoded videos in High Sierra and Mojave (and above), where OS support already exists.

**Comment by packagesdev** [comment]
It's the OS (or at least AV Foundation) that does not consider these videos to be playable:

AVURLAsset *tAVAsset=[AVURLAsset URLAssetWithURL:inURL options:nil];
    
    if (tAVAsset.isPlayable==NO)
    {
        // A COMPLETER
        
        return NO;
    }
