### ISSUE TITLE
Adding a video via the plus symbol crashes the app

### ISSUE THREAD

**Issue by markorapaic** [packagesdev/savehollywood#10]
Just a heads up, when trying to add a video by using the "plus" button, the app fails. However dragging a video into the video area, works just fine.

**Comment by packagesdev** [comment]
Hi,

it's a known issue in macOS Mojave. The problem is on Apple's side and they have been unable to fix in all the macOS Mojave minor updates. This is quite probably related to the changes they made to somehow sandbox screensavers.
