### ISSUE TITLE
Support Webm video format

### ISSUE THREAD

**Issue by ysm0622** [packagesdev/savehollywood#12]
Please support webm video format.

**Comment by packagesdev** [comment]
Noted. But the #1 priority is to get the screensaver works correctly on macOS Mojave (Apple needs to fix its bugs) and on macOS Catalina (Apple needs to stop introducing even more bugs without any official workaround).

**Comment by JayHoltslander** [comment]
+1. Having to convert (and enlarge as a side-effect) a 4K webm video to mp4 this very moment for this reason.
