### ISSUE TITLE
Unable to add any video

### ISSUE THREAD

**Issue by antoneliasson18** [packagesdev/savehollywood#17]
When I click "Add" on any video, in any format, nothing happens.

**Comment by MDanihy** [comment]
I assume you are referring to the + symbol.  Need more information, what OS version are you running, if Big Sur, then you would need to install Rosetta2

**Comment by antoneliasson18** [comment]
No I can click the + button, which brings up the file selector. However, nothing happens when I click "Add". I am able to drag a file into the screen saver settings, and it's previewed in the screen saver preview window, but when clicking "Preview", or when launching the screen saver I get "No videos" as the screen saver.

Tried and replicated on both a mac mini i7 and a MBP i7, on Big Sur, so Rosetta2 shouldn't be needed? 

Thanks!

**Comment by MDanihy** [comment]
Did you read the entire thread and place the videos in the correct directory?

**Comment by antoneliasson18** [comment]
Great, that did the trick, thanks!
