### ISSUE TITLE
Still being maintained / alternatives?

### ISSUE THREAD

**Issue by mjbaldwin** [packagesdev/savehollywood#18]
I wanted to use Save Hollywood to use scenes from my rip of Planet Earth as a screensaver, but it doesn't work on Monterey -- previous workarounds (#11) might work but all my videos are on an external drive.

But does anyone know if this screen saver is totally dead, or if it might start getting fixes again someday, or if there are any good alternatives? On the official website, there's no contact information.

**Comment by packagesdev** [comment]
The developer is busy with 2 other projects and is waiting for Apple to publish the modern API for screensavers that Apple uses for its own screen savers but does not share with 3rd party developers because 3rd party developers are not worthy of Apple's APIs.

**Comment by mjbaldwin** [comment]
Thanks so much for the info. That totally sucks about the lack of API, I can't believe there's no good sandbox permission models, ugh, or that Apple hasn't fixed that in how many new major versions of macOS? Anyways, thanks again.
