### ISSUE TITLE
Mojave  - dark mode

### ISSUE THREAD

**Issue by johndpope** [packagesdev/savehollywood#6]
<img width="662" alt="screen shot 2018-09-19 at 10 30 28 am" src="https://user-images.githubusercontent.com/289994/45759963-1812c680-bbf7-11e8-8f06-64a861c9fc30.png">

seems like xcode upgrades it successfully - but doesn't seem to take.
<img width="1065" alt="screen shot 2018-09-19 at 10 31 29 am" src="https://user-images.githubusercontent.com/289994/45760092-4bedec00-bbf7-11e8-8704-681ee3f56fc9.png">

**Comment by packagesdev** [comment]
Dark Appearance support should be available soon.

**Comment by johndpope** [comment]
I found this swift screen saver - https://github.com/JohnCoates/Aerial/issues/463
yielding to this repo.
